### PR TITLE
correct CNT vocab to be ContentAsText 

### PR DESCRIPTION
**Pull request by ndushay**
(it was AsText) per http://www.w3.org/TR/Content-in-RDF10/#ContentAsTextClass

@elrayle

### CODE REVIEW

**Comment by ndushay** [comment]
BTW:  the tests didn't all pass.  Some due to a more recent version of rspec (it's now "skip" not "pending"), but others seem like real errors:

Failures:

  1) LD4L::OpenAnnotationRDF::CommentAnnotation big complex graphs should allow access to deep nodes
     Failure/Error: LD4L::OpenAnnotationRDF::CommentAnnotation.property :item, :predicate => RDF::DC.relation, :class_name => DummyDocument
     ArgumentError:
       item is a keyword and not an acceptable property name.
     # /Users/ndushay/.rvm/gems/ruby-2.1.2@ld4l-oa-gem_no-rails/bundler/gems/ActiveTriples-d87d38c89e0f/lib/active_triples/properties.rb:44:in `property'
     # ./spec/ld4l/open_annotation_rdf/comment_annotation_spec.rb:502:in `block (3 levels) in <top (required)>'

  2) LD4L::OpenAnnotationRDF::CommentBody format should be changeable
     Failure/Error: expect(subject.format.first.rdf_subject).to eq  new_format
     NoMethodError:
       undefined method `rdf_subject' for "text/xml":String
     # ./spec/ld4l/open_annotation_rdf/comment_body_spec.rb:139:in `block (3 levels) in <top (required)>'

  3) LD4L::OpenAnnotationRDF::SemanticTagAnnotation #destroy! with annotation body and body is set on the annotation should empty the graph and remove it from the parent
     Failure/Error: expect(subject.hasBody).to be_empty
       expected `[#<ActiveTriples::Resource:0x3fd1ba1d2038(default)>].empty?` to return true, got false
     # ./spec/ld4l/open_annotation_rdf/semantic_tag_annotation_spec.rb:363:in `block (5 levels) in <top (required)>'

  4) LD4L::OpenAnnotationRDF::SemanticTagAnnotation attributes with unmodeled data should return generic Resources
     Failure/Error: expect(subject.attributes[RDF::DC.relation.to_s].first).to be_a ActiveTriples::Resource
     NoMethodError:
       undefined method `first' for nil:NilClass
     # ./spec/ld4l/open_annotation_rdf/semantic_tag_annotation_spec.rb:412:in `block (4 levels) in <top (required)>'

  5) LD4L::OpenAnnotationRDF::SemanticTagAnnotation attributes with unmodeled data should build deep data for Resources
     Failure/Error: expect(subject.attributes[RDF::DC.relation.to_s].first.get_values(RDF::DC.relation).
     NoMethodError:
       undefined method `first' for nil:NilClass
     # ./spec/ld4l/open_annotation_rdf/semantic_tag_annotation_spec.rb:416:in `block (4 levels) in <top (required)>'

  6) LD4L::OpenAnnotationRDF::SemanticTagAnnotation attributes with unmodeled data should include deep data in serializable_hash
     Failure/Error: expect(subject.serializable_hash[RDF::DC.relation.to_s].first.get_values(RDF::DC.relation).
     NoMethodError:
       undefined method `first' for nil:NilClass
     # ./spec/ld4l/open_annotation_rdf/semantic_tag_annotation_spec.rb:421:in `block (4 levels) in <top (required)>'

  7) LD4L::OpenAnnotationRDF::TagAnnotation #setTag when new value is nil should throw invalid aguement exception FIXED
     Expected pending 'need to write this test' to fail. No Error was raised.
     # ./spec/ld4l/open_annotation_rdf/tag_annotation_spec.rb:114

  8) LD4L::OpenAnnotationRDF::TagAnnotation #setTag when new value is same as old value should return the existing TabBody unchanged FIXED
     Expected pending 'need to write this test' to fail. No Error was raised.
     # ./spec/ld4l/open_annotation_rdf/tag_annotation_spec.rb:120

  9) LD4L::OpenAnnotationRDF::TagAnnotation #setTag when config enforces unique tags and tag already exists as a TagBody should resume the existing LD4L::OpenAnnotationRDF::TagBody and set hasBody property to it
     Failure/Error: expect(subject.hasBody.first.rdf_subject.to_s).to eq 'http://example.org/existing_tag'
       
       expected: "http://example.org/existing_tag"
            got: "http://localhost/38ce34f4-9813-4aa0-a420-e926b4b35483"
       
       (compared using ==)
     # ./spec/ld4l/open_annotation_rdf/tag_annotation_spec.rb:152:in `block (5 levels) in <top (required)>'

  10) LD4L::OpenAnnotationRDF::TagAnnotation #setTag when config does not enforce unique tags and tag doesn't already exist as a TagBody should create an instance of LD4L::OpenAnnotationRDF::TagBody and set hasBody property to it FIXED
     Expected pending 'need to write this test' to fail. No Error was raised.
     # ./spec/ld4l/open_annotation_rdf/tag_annotation_spec.rb:167

  11) LD4L::OpenAnnotationRDF::TagAnnotation #setTag when config does not enforce unique tags and tag already exists as a TagBody should resume the existing LD4L::OpenAnnotationRDF::TagBody and set hasBody property to it FIXED
     Expected pending 'need to write this test' to fail. No Error was raised.
     # ./spec/ld4l/open_annotation_rdf/tag_annotation_spec.rb:186

  12) LD4L::OpenAnnotationRDF::TagAnnotation #persist! when the repository is set and the annotation is not a blank node and body is set should persist body to the repository
     Failure/Error: expect(tb).to be_persisted
       expected  to respond to `persisted?`
     # ./spec/ld4l/open_annotation_rdf/tag_annotation_spec.rb:359:in `block (6 levels) in <top (required)>'

  13) LD4L::OpenAnnotationRDF::TagAnnotation big complex graphs should allow access to deep nodes
     Failure/Error: LD4L::OpenAnnotationRDF::TagAnnotation.property :item, :predicate => RDF::DC.relation, :class_name => DummyDocument
     ArgumentError:
       item is a keyword and not an acceptable property name.
     # /Users/ndushay/.rvm/gems/ruby-2.1.2@ld4l-oa-gem_no-rails/bundler/gems/ActiveTriples-d87d38c89e0f/lib/active_triples/properties.rb:44:in `property'
     # ./spec/ld4l/open_annotation_rdf/tag_annotation_spec.rb:591:in `block (3 levels) in <top (required)>'

  14) LD4L::OpenAnnotationRDF::TagBody #fetch_by_tag_value should not find non-existent tag FIXED
     Expected pending 'Need to write' to fail. No Error was raised.
     # ./spec/ld4l/open_annotation_rdf/tag_body_spec.rb:88

  15) LD4L::OpenAnnotationRDF::TagBody #fetch_by_tag_value should find existent tag FIXED
     Expected pending 'Need to write' to fail. No Error was raised.
     # ./spec/ld4l/open_annotation_rdf/tag_body_spec.rb:92

Finished in 2.06 seconds (files took 1.74 seconds to load)
359 examples, 15 failures

**Comment by ndushay** [comment]
p.s.  you can delete the branch after you do the merge.  :-)

**Comment by azaroth42** [comment]
+1

Annotations can be validated here:
    http://austese.net/lorestore/validate.html

to see if they're good or not (thanks @AnnaGerber!)


On Mon, Jan 5, 2015 at 4:44 PM, Naomi Dushay <notifications@github.com>
wrote:

> p.s. you can delete the branch after you do the merge. :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ld4l/open_annotation_rdf/pull/2#issuecomment-68808918>
> .
>



-- 
Rob Sanderson
Information Standards Advocate
Digital Library Systems and Services
Stanford, CA 94305

**Comment by ndushay** [comment]
We could consider trying to contrib back to RDF vocabs:

https://github.com/sul-dlss/rdf-open_annotation/tree/master/lib/rdf

**Pull request merged**
